#!/usr/bin/env node
'use strict';

const fs = require('fs');
const path = require('path');
const sharp = require('sharp');

const ROOT = __dirname;
const INSTAGRAM_URL = 'https://www.instagram.com/phieetle/';
const CONTACT_HREF = 'mailto:sophiecmckenzie28@gmail.com';
const IMAGE_EXT = new Set(['.png', '.jpg', '.jpeg', '.gif', '.webp', '.heic', '.avif']);
const THUMB_MAX_WIDTH = 1200;
const THUMB_QUALITY = 85;

function isImage(f) {
  return IMAGE_EXT.has(path.extname(f).toLowerCase());
}

function parseGalleryName(filename) {
  const name = path.parse(filename).name;
  const withYear = name.match(/^(.*),\s*(\d{4})[.\s]*$/);
  if (withYear) return { title: withYear[1].trim(), year: withYear[2] };
  const title = name.replace(/[.\s]+$/, '').trim();
  return title ? { title, year: null } : null;
}

function parseWithinTarget(filename) {
  const name = path.parse(filename).name;
  if (!name.startsWith('IMAGE WITHIN ')) return null;
  return name.slice('IMAGE WITHIN '.length).replace(/\d+$/, '').trim();
}

function scanGallery(dirName) {
  const absDir = path.join(ROOT, dirName);
  const files = fs.readdirSync(absDir).filter(isImage).sort();
  const gallery = [];
  const withinFiles = [];

  for (const f of files) {
    if (f.startsWith('IMAGE WITHIN ')) {
      withinFiles.push(f);
    } else {
      const parsed = parseGalleryName(f);
      if (parsed) gallery.push({ file: `${dirName}/${f}`, title: parsed.title, year: parsed.year });
    }
  }

  const lookup = {};
  for (const item of gallery) lookup[item.title.toLowerCase()] = item.title;

  const withinMap = {};
  for (const f of withinFiles) {
    const target = parseWithinTarget(f);
    if (!target) continue;
    const matched = lookup[target.toLowerCase()];
    if (matched) {
      if (!withinMap[matched]) withinMap[matched] = [];
      withinMap[matched].push(`${dirName}/${f}`);
    }
  }

  return { gallery, withinMap };
}

function scanSketches(dirName) {
  const absDir = path.join(ROOT, dirName);
  return fs.readdirSync(absDir).filter(isImage).sort().map(f => ({ file: `${dirName}/${f}` }));
}

function applyOrder(gallery, pinnedTitles) {
  if (!pinnedTitles || !pinnedTitles.length) return gallery;
  const pinned = [];
  const rest = [];
  for (const item of gallery) {
    if (pinnedTitles.includes(item.title)) pinned.push(item);
    else rest.push(item);
  }
  pinned.sort((a, b) => pinnedTitles.indexOf(a.title) - pinnedTitles.indexOf(b.title));
  return [...pinned, ...rest];
}

async function generateThumb(filePath) {
  const [dir, filename] = filePath.split('/');
  const thumbDir = path.join(ROOT, 'thumbs', dir);
  if (!fs.existsSync(thumbDir)) fs.mkdirSync(thumbDir, { recursive: true });

  const thumbFilename = path.parse(filename).name.replace(/[.\s]+$/, '') + '.jpg';
  const thumbRel = `thumbs/${dir}/${thumbFilename}`;
  const thumbAbs = path.join(ROOT, thumbRel);
  const srcAbs = path.join(ROOT, filePath);

  const srcMtime = fs.statSync(srcAbs).mtime;
  if (fs.existsSync(thumbAbs) && fs.statSync(thumbAbs).mtime > srcMtime) return thumbRel;

  await sharp(srcAbs)
    .resize({ width: THUMB_MAX_WIDTH, withoutEnlargement: true })
    .jpeg({ quality: THUMB_QUALITY })
    .toFile(thumbAbs);

  return thumbRel;
}

async function main() {
  const orderFile = path.join(ROOT, 'gallery-order.json');
  const order = fs.existsSync(orderFile) ? JSON.parse(fs.readFileSync(orderFile, 'utf8')) : {};

  const { gallery: illustrations, withinMap: illustrationWithin } = scanGallery('illustrations');
  const { gallery: patterns, withinMap: patternWithin } = scanGallery('surfaceandpattern');
  const sketches = scanSketches('sketches');

  const orderedIllustrations = applyOrder(illustrations, order.illustrations || []);
  const orderedPatterns = applyOrder(patterns, order.patterns || []);

  console.log('Generating thumbnails...');
  for (const item of orderedIllustrations) {
    process.stdout.write(`  ${item.title}... `);
    item.thumb = await generateThumb(item.file);
    console.log('done');
  }
  for (const item of orderedPatterns) {
    process.stdout.write(`  ${item.title}... `);
    item.thumb = await generateThumb(item.file);
    console.log('done');
  }
  for (const item of sketches) {
    item.thumb = await generateThumb(item.file);
  }

  const output = [
    '// Auto-generated by build.js — run "node build.js" after adding images.',
    `var INSTAGRAM_URL = '${INSTAGRAM_URL}';`,
    `var CONTACT_HREF = '${CONTACT_HREF}';`,
    '',
    `var ILLUSTRATIONS = ${JSON.stringify(orderedIllustrations, null, 2)};`,
    '',
    `var ILLUSTRATION_WITHIN = ${JSON.stringify(illustrationWithin, null, 2)};`,
    '',
    `var PATTERNS = ${JSON.stringify(orderedPatterns, null, 2)};`,
    '',
    `var PATTERN_WITHIN = ${JSON.stringify(patternWithin, null, 2)};`,
    '',
    `var SKETCHES = ${JSON.stringify(sketches, null, 2)};`,
  ].join('\n');

  fs.writeFileSync(path.join(ROOT, 'gallery-data.js'), output, 'utf8');

  console.log('\ngallery-data.js updated!');
  console.log(`  Illustrations : ${orderedIllustrations.length}`);
  console.log(`  Patterns      : ${orderedPatterns.length}`);
  console.log(`  Sketches      : ${sketches.length}`);
}

main().catch(err => { console.error(err); process.exit(1); });
