// UI functions — image data lives in gallery-data.js (auto-generated by build.js)

function escHtml(str) {
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function toSrc(filePath) {
  return filePath.split('/').map(function (part) {
    return encodeURIComponent(part);
  }).join('/');
}

var IG_SVG = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="2" y="2" width="20" height="20" rx="5" ry="5"/><circle cx="12" cy="12" r="4.5"/><circle cx="17.5" cy="6.5" r="1" fill="currentColor" stroke="none"/></svg>';

function buildHeader(activePage) {
  var navLinks = [
    { label: 'Illustration', href: 'index.html', key: 'illustration' },
    { label: 'Pattern', href: 'pattern.html', key: 'pattern' },
    { label: 'Sketches', href: 'sketches.html', key: 'sketches' },
    { label: 'About', href: 'about.html', key: 'about' },
  ];

  var links = navLinks.map(function (item) {
    var cls = activePage === item.key ? ' class="active"' : '';
    return '<a href="' + item.href + '"' + cls + '>' + item.label + '</a>';
  }).join('\n    ');

  return '<header>\n' +
    '  <div class="header-top">\n' +
    '    <img src="logos/logo.png" alt="Sophie McKenzie logo" class="logo-img">\n' +
    '  </div>\n' +
    '  <nav>\n' +
    '    ' + links + '\n' +
    '    <a href="' + INSTAGRAM_URL + '" class="nav-instagram" target="_blank" rel="noopener noreferrer" aria-label="Instagram">' + IG_SVG + '</a>\n' +
    '  </nav>\n' +
    '</header>';
}

function buildGalleryGrid(items, galleryType) {
  var itemsHtml = items.map(function (item) {
    if (galleryType === 'sketches') {
      var sketchUrl = 'image.html?gallery=sketches&file=' + encodeURIComponent(item.file);
      return '<a href="' + sketchUrl + '" class="gallery-item">\n' +
        '  <div class="gallery-item-inner">\n' +
        '    <img src="' + toSrc(item.thumb || item.file) + '" alt="Sketch" loading="lazy">\n' +
        '  </div>\n' +
        '</a>';
    }
    var detailUrl = 'image.html?gallery=' + encodeURIComponent(galleryType) +
      '&title=' + encodeURIComponent(item.title);
    return '<a href="' + detailUrl + '" class="gallery-item">\n' +
      '  <div class="gallery-item-inner">\n' +
      '    <img src="' + toSrc(item.thumb || item.file) + '" alt="' + escHtml(item.title) + '" loading="lazy">\n' +
      '    <div class="item-title-overlay">' + escHtml(item.title) + '</div>\n' +
      '  </div>\n' +
      '</a>';
  }).join('\n');

  return '<div class="gallery-grid">\n' + itemsHtml + '\n</div>';
}
