// Auto-generated by build.js — run "node build.js" after adding images.
var INSTAGRAM_URL = 'https://www.instagram.com/phieetle/';
var CONTACT_HREF = 'mailto:sophiecmckenzie28@gmail.com';

var ILLUSTRATIONS = [
  {
    "file": "illustrations/Aliens, 2025.PNG",
    "title": "Aliens",
    "year": "2025"
  },
  {
    "file": "illustrations/American Woodcock, 2026.PNG",
    "title": "American Woodcock",
    "year": "2026"
  },
  {
    "file": "illustrations/Bath Time, 2026..png",
    "title": "Bath Time",
    "year": "2026"
  },
  {
    "file": "illustrations/Breakfast Party, 2026..png",
    "title": "Breakfast Party",
    "year": "2026"
  },
  {
    "file": "illustrations/Bug Picnic, 2026..PNG",
    "title": "Bug Picnic",
    "year": "2026"
  },
  {
    "file": "illustrations/Coven Tots, 2025.png",
    "title": "Coven Tots",
    "year": "2025"
  },
  {
    "file": "illustrations/Critter Crew.jpeg",
    "title": "Critter Crew",
    "year": null
  },
  {
    "file": "illustrations/Fisherman, 2026..jpg",
    "title": "Fisherman",
    "year": "2026"
  },
  {
    "file": "illustrations/Fishing.jpeg",
    "title": "Fishing",
    "year": null
  },
  {
    "file": "illustrations/Invasive Snails Poster, 2026.PNG",
    "title": "Invasive Snails Poster",
    "year": "2026"
  },
  {
    "file": "illustrations/Leopard.jpeg",
    "title": "Leopard",
    "year": null
  },
  {
    "file": "illustrations/Minnie.jpeg",
    "title": "Minnie",
    "year": null
  },
  {
    "file": "illustrations/PO Box Outerspace, 2026.PNG",
    "title": "PO Box Outerspace",
    "year": "2026"
  },
  {
    "file": "illustrations/Skeleton Flowers, 2025.PNG",
    "title": "Skeleton Flowers",
    "year": "2025"
  },
  {
    "file": "illustrations/Snake, 2026.png",
    "title": "Snake",
    "year": "2026"
  },
  {
    "file": "illustrations/Two Tigers.png",
    "title": "Two Tigers",
    "year": null
  },
  {
    "file": "illustrations/Warby Parker, 2026..png",
    "title": "Warby Parker",
    "year": "2026"
  }
];

var ILLUSTRATION_WITHIN = {
  "American Woodcock": [
    "illustrations/IMAGE WITHIN American Woodcock1.jpg",
    "illustrations/IMAGE WITHIN American Woodcock2.PNG"
  ],
  "Bug Picnic": [
    "illustrations/IMAGE WITHIN Bug Picnic1.PNG",
    "illustrations/IMAGE WITHIN Bug Picnic2.PNG",
    "illustrations/IMAGE WITHIN Bug Picnic3.PNG",
    "illustrations/IMAGE WITHIN Bug Picnic4.PNG",
    "illustrations/IMAGE WITHIN Bug Picnic5.PNG"
  ],
  "PO Box Outerspace": [
    "illustrations/IMAGE WITHIN PO Box outerspace.PNG"
  ],
  "Two Tigers": [
    "illustrations/IMAGE WITHIN Two Tigers 2.jpeg",
    "illustrations/IMAGE WITHIN Two Tigers.jpeg"
  ]
};

var PATTERNS = [
  {
    "file": "surfaceandpattern/Apple Juicy Repeat, 2026..png",
    "title": "Apple Juicy Repeat",
    "year": "2026"
  },
  {
    "file": "surfaceandpattern/Critter Bed Flat, 2026.PNG",
    "title": "Critter Bed Flat",
    "year": "2026"
  },
  {
    "file": "surfaceandpattern/Flower Sheets, 2026..PNG",
    "title": "Flower Sheets",
    "year": "2026"
  },
  {
    "file": "surfaceandpattern/Flowers Repeat.png",
    "title": "Flowers Repeat",
    "year": null
  },
  {
    "file": "surfaceandpattern/Pears Repeat, 2026.PNG",
    "title": "Pears Repeat",
    "year": "2026"
  },
  {
    "file": "surfaceandpattern/Dachshund Pattern.png",
    "title": "Dachshund Pattern",
    "year": null
  }
];

var PATTERN_WITHIN = {
  "Apple Juicy Repeat": [
    "surfaceandpattern/IMAGE WITHIN Apple Juicy Repeat1.png"
  ],
  "Critter Bed Flat": [
    "surfaceandpattern/IMAGE WITHIN Critter Bed Flat1.png"
  ],
  "Pears Repeat": [
    "surfaceandpattern/IMAGE WITHIN Pears Repeat1.PNG"
  ],
  "Dachshund Pattern": [
    "surfaceandpattern/IMAGE WITHIN Dachshund Pattern.png"
  ]
};

var SKETCHES = [
  {
    "file": "sketches/21C06121-E63F-486A-B1BD-51C4BBF195CD_1_105_c.jpeg"
  },
  {
    "file": "sketches/37DB1F8D-52FC-4995-BA09-2034A9DBA577_1_105_c.jpeg"
  },
  {
    "file": "sketches/9257C92E-6D49-4FBF-AD30-774C4ADFE315_1_105_c.jpeg"
  },
  {
    "file": "sketches/IMG_0611.PNG"
  },
  {
    "file": "sketches/IMG_0710.PNG"
  },
  {
    "file": "sketches/IMG_0716.PNG"
  },
  {
    "file": "sketches/IMG_0717.PNG"
  }
];